version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "6000:6000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/userdb"

  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  mysql-data:
